- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Install packages"
  apt:
    state: latest
    pkg:
      - python-pip
      - python-dev
      - virtualenv
      - python-rpi.gpio
  register: install

- name: "Install libs"
  pip:
    name: flask