---

- name: "Check all hosts accessible"
  assert:
    that:
    - ansible_play_hosts == ansible_play_hosts_all

- name: "Ensure hostname set"
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname

- name: "Ensure all hostnames in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_host }}.+$'
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"
  become: true
  register: hostname

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "Install apt tools"
  apt:
    state: latest
    pkg:
      - aptitude
      - apt-transport-https

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "apt-get upgrade"
  apt:
    upgrade: full
  register: upgrade

- name: "Add apt signing key from official docker repo"
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: "Add docker official repository for Debian Stretch"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: "Index new repo into the cache"
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: "Install prerequisites"
  apt:
    state: latest
    pkg:
    - net-tools
    - sudo
    - sendmail-bin
    - python-setuptools
    - python-pip
    - ntp
    - telnet
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - ipvsadm
    - dnsutils
    - docker-ce
    - htop

- name: "Install libraries"
  pip:
    name: docker

- name: "Reboot"
  shell: sleep 5 && sync && shutdown -r now "Ansible Reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: hostname.changed or upgrade.changed
  register: rebooted

- name: "Wait for up"
  wait_for_connection:
    delay: 5
    connect_timeout: 5
    sleep: 1
    timeout: 240
  when: rebooted.changed

- name: "Pass bridged IPv4 traffic to iptables' chains"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present

- name: "Add Google Cloud repo key"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: "Add Kubernetes to apt repositories"
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes
    update_cache: yes

- name: "Install k8s ({{ kubernetes_package_version }})"
  apt:
    state: present
    force: yes
    update_cache: yes
    pkg:
    - kubelet={{ kubernetes_package_version }}
    - kubeadm={{ kubernetes_package_version }}
    - kubectl={{ kubernetes_package_version }}
    - kubernetes-cni
  ignore_errors: yes

- name: "Update /etc/docker/daemon.json to use docker-registry mirror on router"
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: "Select cgroup driver"
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: 'ExecStart.+$'
    line: "ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock --exec-opt native.cgroupdriver=cgroupfs"
    state: present
  become: true
  register: docker

- name: "Restart docker"
  service:
    name: docker
    state: restarted

- name: "Sleep"
  delegate_to: localhost
  shell: sleep 10
  become: false

- name: "kubeadmn config images pull"
  shell: kubeadm config images pull --kubernetes-version={{ kubernetes_version }}
  become: true

- name: "Reset K8S"
  shell: kubeadm reset -f
  register: kubeadm_reset
  become: true

- name: "Create net.d"
  file:
    path: "/etc/cni/net.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true
