---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piphp
  labels:
    app: piphp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: piphp
  template:
    metadata:
      labels:
        app: piphp
    spec:
      containers:
        - name: stack
          image: 11.0.0.1:5001/helmuthva/arm32v7-docker-php-apache
          ports:
            - containerPort: 80
