#!/usr/bin/env bash

cd "$(dirname "$0")"

helm repo add sp https://stefanprodan.github.io/k8s-podinfo
kubectl create namespace podinfo
helm install --name podinfo --namespace podinfo sp/podinfo -f values.yaml
