# Based on https://github.com/heketi/heketi/blob/v6.0.0/extras/kubernetes/heketi-deployment.json
---
kind: Secret
apiVersion: v1
metadata:
  name: heketi-db-backup
  namespace: {{ k8s_heketi_gluster_namespace }}
  labels:
    glusterfs: heketi-db
    heketi: db
data:
#  heketi.db: ""
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: heketi
  namespace: {{ k8s_heketi_gluster_namespace }}
  labels:
    glusterfs: heketi-service
    deploy-heketi: support
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    name: heketi
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: heketi
  namespace: storage-heketi
  labels:
    glusterfs: heketi-deployment
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: 1
  template:
    metadata:
      name: heketi
      labels:
        name: heketi
        glusterfs: heketi-pod
    spec:
      serviceAccountName: heketi-service-account
      containers:
      - image: {{ k8s_heketi_heketi_image }}
        imagePullPolicy: Always
        name: heketi
        env:
        - name: HEKETI_EXECUTOR
          value: "kubernetes"
        - name: HEKETI_KUBE_NAMESPACE
          value: "storage-heketi"
        - name: HEKETI_DB_PATH
          value: "/var/lib/heketi/heketi.db"
        - name: HEKETI_FSTAB
          value: "/var/lib/heketi/fstab"
        - name: HEKETI_SNAPSHOT_LIMIT
          value: "14"
        - name: HEKETI_KUBE_GLUSTER_DAEMONSET
          value: "y"
        # - name: HEKETI_ADMIN_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: heketi-secret
        #       key: key
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /backupdb
          name: heketi-db-secret
        - name: db
          mountPath: /var/lib/heketi
#        - name: config
#          mountPath: /etc/heketi
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: /hello
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: /hello
            port: 8080
      volumes:
      - name: db
        glusterfs:
          endpoints: heketi-storage-endpoints
          path: heketidbstorage
      - name: heketi-db-secret
        secret:
          secretName: heketi-db-backup
      # - name: config
      #   secret:
      #     secretName: heketi-config-secret
