kind: ServiceAccount
apiVersion: v1
metadata:
  name: heketi-service-account
  namespace: {{ k8s_heketi_gluster_namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: storage-heketi-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: heketi-service-account
  namespace: {{ k8s_heketi_gluster_namespace }}
