---

- name: "Check all hosts accessible"
  assert:
    that:
      - ansible_play_hosts == ansible_play_hosts_all

- name: "Stop docker"
  service:
    name: docker
    state: stopped
  ignore_errors: yes

- name: "Unmount"
  mount:
    path: /mnt/thumb
    src: "{{ thumb.partition }}"
    fstype: ext4
    state: unmounted

- name: "Wipe signature and partitions"
  command: >
    wipefs --all --force {{ thumb.device }}

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: "Install prerequisites"
  apt:
    state: latest
    pkg:
      - parted

- name: "Partition"
  parted:
    device: "{{ thumb.device }}"
    number: 1
    state: present

- name: "Create a ext4 filesystem"
  filesystem:
    fstype: ext4
    dev: "{{ thumb.partition }}"

- name: "Mount"
  mount:
    path: /mnt/thumb
    src: "{{ thumb.partition }}"
    fstype: ext4
    state: mounted
    opts: nofail

- name: "Start docker"
  service:
    name: docker
    state: started