- hosts: all
  serial: 1
  roles:
    - nodes

- hosts: master
  roles:
    - masters
    - dashboard

- hosts: all:!master
  serial: 1
  roles:
    - workers

- hosts: all
  serial: 1
  roles:
  - gluster-heketi

- hosts: master
  roles:
  - role: helm
    setup: true
