- hosts: all
  roles:
    - nodes

- hosts: master
  roles:
    - masters
    - dashboard

- hosts: all:!master
  roles:
    - workers

#- hosts: all
#  roles:
#  - gluster-heketi

- hosts: master
  roles:
  - role: helm
    setup: true
