- hosts: all
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      autoclean: yes
      autoremove: yes
      cache_valid_time: 86400
  - name: "Install prerequisites"
    apt:
      state: latest
      pkg:
        - parted
  - name: "Wipe signature and partitions of thumb drives"
    command: >
      wipefs --all --force /dev/sdb
