galaxy_info:
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Setup a GlusterFS cluster with Heketi REST API on Kubernetes
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []

dependencies: []
