# If True make this the default storage class for dynamically provisioned volumes
k8s_heketi_gluster_default_storageclass: true

# If True nodes will be labeled and tainted NoSchedule
k8s_heketi_gluster_force_dedicated: false

# Kubernetes tolerations to allow GlusterFS + Heketi on master
k8s_heketi_gluster_tolerations:
  - key: node-role.kubernetes.io/master
    operator: Equal
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Equal
    effect: NoSchedule

# Kubernetes node-selector
k8s_heketi_gluster_nodeselector:
  storage: "true"

# The underlying raw storage device
k8s_heketi_gluster_storage_device: "/dev/gluster"

# Gluster docker image
k8s_heketi_gluster_image: "gluster/gluster-centos:latest"

# Heketi docker image
k8s_heketi_heketi_image: "heketi/heketi"

# Heketi distribution
k8s_heketi_distribution: "https://github.com/heketi/heketi/releases/download/v9.0.0/heketi-client-v9.0.0.linux.amd64.tar.gz"

# kubectl binary
k8s_heketi_gluster_kubectl: "kubectl"

# Namespace for all resources
k8s_heketi_gluster_namespace: "storage-heketi"

# Require kernel modules for Gluster Heketi
k8s_heketi_gluster_required_modules:
- dm_snapshot
- dm_mirror
- dm_thin_pool
