---
- hosts: all

  connection: local

  tasks:
    - name: Add mappings to /etc/hosts
      tags:
        - hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} max {{ item.name }}"
      with_items:
        - { name: max-two, ip: 12.0.0.102 }
        - { name: max-two.dev, ip: 12.0.0.102 }
        - { name: max-three, ip: 12.0.0.103 }
        - { name: max-three.dev, ip: 12.0.0.103 }
        - { name: httpd.max.local, ip: 12.0.0.102 }
        - { name: traefik-ui.max.local, ip: 12.0.0.102 }
        - { name: prometheus.max.local, ip: 12.0.0.102 }
        - { name: alertmanager.max.local, ip: 12.0.0.102 }
        - { name: pushgateway.max.local, ip: 12.0.0.102 }
        - { name: grafana.max.local, ip: 12.0.0.102 }
