#!/usr/bin/env bash

cd "$(dirname "$0")/../.."

workstation/bin/flash --force --bootconf "host/config/config.txt" --hostname "ceil-router" --userdata host/config/router.yaml host/image/hypriotos-rpi-v1.10.0.img.zip
