#!/usr/bin/env bash

cd "$(dirname "$0")/../.."

workstation/bin/flash --force --bootconf "host/config/config.txt" --hostname "ceil-two" --userdata host/config/node.yaml host/image/hypriotos-rpi-v1.10.0.img.zip